services:
  mysql:
    image: mysql:8.0
    container_name: pizzacode_mysql_container
    environment:
      MYSQL_DATABASE: pizzacode
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local